### ISSUE TITLE
ScheduledTask: Should the user defaulting to "System" if the ExecuteAsCredential property is null be changed?

### ISSUE THREAD

**Issue by djwork** [PowerShell/ComputerManagementDsc#191]
Hi Everyone
                   As part of working on implementing BuiltInAccount in my fork, I noticed the default behavior of the ScheduledTask DSCR is to default the user running the task to System if the ExecuteAsCredential property is null. My security team is always on developers to avoid running services or tasks as System unless absolutely required.

How about defaulting to "NT AUTHORITY\LocalService" instead? This is the least privileged builtin account. The issue with this is it may break existing Scheduled Tasks that rely on the basically unlimited privileges of the System account.

Thoughts?

[Good summary of the available service accounts](https://stackoverflow.com/questions/510170/the-difference-between-the-local-system-account-and-the-network-service-acco)

**Comment by PlagueHO** [comment]
This does sound like a good idea, but would definitely be a breaking change and would definitely affect a lot of users. It is worth considering though. @johlju ?

**Comment by johlju** [comment]
I understand this, and I'm all for low privilege thinking. Although, this will be a breaking change which a lot of user might not realize when things go wrong (badly). If they expect that a configuration creates a schedule task as SYSTEM, and when they rebuild the system using the configuration "tomorrow", a job that runs rarely might start breaking. 
My thinking is that if an organization that are using low privilege account, they want to specify those account in the configuration to know that they will never be broken by a future breaking change. 
So suggest leaving it as is, and those that want to use low privilege accounts can do so in the configuration.

But if the rest of the community is in favor of changing the default account, then I'm okay with it. And if we should introduce a breaking change, then it would be a good time to do it before the next release, since we already have a breaking change merged. 🙂

**Comment by johlju** [comment]
Labeled this issue as breaking change, just for everyone to know that it is a breaking change, regardless if this will be resolved or not. 🙂

**Comment by djwork** [comment]
>  If they expect that a configuration creates a schedule task as SYSTEM, and when they "tomorrow" rebuild the system using the configuration, a job that runs rarely might start breaking.

With the above in mind may be the less nasty surprise would be to not default the user to anything, instead throw an exception if the users has not defined as one of the following; ExecuteAsCredential,  BuiltInAccount or ExecuteAsGMSA.

Migrating users who want the original behavior can set BuiltInAccount = 'SYSTEM'
