### ISSUE TITLE
Move SystemLocale resource from SystemLocaleDSC to xComputerManagement

### ISSUE THREAD

**Issue by lfshr** [PowerShell/ComputerManagementDsc#50]
The SystemLocale resource currently resides inside of it's own module (SystemLocaleDSC).
I believe it makes more sense inside of xComputerManagement\xComputer resource as an optional parameter.

Let me know what you guys think. I've already submitted a PR ([#49](https://github.com/PowerShell/xComputerManagement/pull/49))

Liam

**Comment by PlagueHO** [comment]
Thanks for raising the issue @TheFish92 !

I'm Ok with moving the functionality of SystemLocaleDsc into xComputerManagement/xComputer if there is a good reason to do so and if the community agrees this is the way to go. This is a fairly reasonable place for the function.

The only caveat to this is that if it did move this function we really should deprecate SystemLocaleDsc because maintaining this function in two places:
- is a double up of effort
- will result in confusion over which resource people should use
- can result in configs that never go into state

But deprecating a DSC resource isn't a call I'd want to make - there may be a number of people using it. I don't actually use SystemLocaleDsc myself.

@mgreenegit , you originally suggested the SystemLocaleDsc resource - what are your thoughts on moving the functionality over to xComputer as @TheFish92 has suggested?





S

**Comment by mgreenegit** [comment]
While I like that this would be one less thing a configuration author would need to discover, I'm concerned to see a high quality module shift in to one that has not met baseline yet.  It would be great to see xComputerManagement become ComputerManagement and then revisit consolidating.  Just my opinion.

**Comment by TheFish92** [comment]
I only post this request as I naturally looked inside the xComputer resource to try and find the Locale options. The problem I foresee with leaving the resource until baseline is the increase in the number of configuration scripts that would use the SystemLocale resource. Moving this resource in 6 months later would add another 6 months of potential configuration scripts on top of the current scripts that use the SystemLocalDSC module.

It may be worth making the decision now, and if you guys agree it's a better place, adding a warning message of some kind to the current SystemLocaleDSC stating that it's becoming obsolete, and leaving it up for a few months to allow for scripts to migrate.

Now is the time to make changes like this, while DSC is still young and the number of DSC Resource scripts are few.

**Comment by mgreenegit** [comment]
Looking at xComputerManagement, it appears to have docs and both integration and unit tests.  @kwirkykat can you comment on the remaining effort to move it out of experimental status?

**Comment by kwirkykat** [comment]
@mgreenegit 2 of the resources still need integration tests. I see some issues PSSA will flag in the resource code (there are no verbose messages in xComputer). This module should probably also be set up for localized strings for the verbose messages especially as we are discussing adding SystemLocale here.

I would say this module is closer than most to becoming high quality since it does already have unit tests, but it definitely still needs some polishing.
@mbreakey3 and I are the only ones from the DSC team that work on the resource kit consistently though, so this work would have to come from the community and be reviewed for the near future.

**Comment by PlagueHO** [comment]
Hi @kwirkykat , @mgreenegit - I'm happy to do the HQRM work on this resource if it will help. Could probably easily get this out by the end of this weekend. I contributed xOfflineDomainJoin so it is already not too far from HQRM - not sure about the others. I'll need to add strings etc and move everything into localization files, but it's mostly cleanup, as you say (thankfully no unit tests :) ). The integration tests can be created for ODJ but they can't actually run in AppVeyor as they'd need an actual ODJ file and a domain. But I could create support to manually execute the tests if you can provide these things.

@TheFish92 - if I do the work on getting this resource to HQRM then you should be able recommit your PR. I did take a look at your PR and would suggest that hard coding the list of valid locale's is not the way to go.

Could you take a look at [SystemLocaleDsc](https://github.com/PowerShell/SystemLocaleDsc/blob/dev/DSCResources/MSFT_SystemLocale/MSFT_SystemLocale.psm1) and see how the validation is done there?

Also, if you could take a look at the [HQRM guidelines](https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md) to make sure your PR meets them.

When I make the HQRM changes, I'll try and keep what you're going to do in mind.

**Comment by TheFish92** [comment]
@PlagueHO I've been looking to sink my teeth into a GitHub project for a while so let me know if there's anything I can fling myself at. I've started writing LocalizedData strings for xComputer.

The hard-coded cultures are for nothing other than intellisense inside of ISE (I'm a sucker for intellisense). Is there a better way to do this in a DSCResource? (such as TabExecution function). The code will work using [CultureInfo]::GetCultures() for validation. The ValidateSet, Values and ValueMap can be removed and it will handle errors as expected (without any further changes)

**Comment by PlagueHO** [comment]
@TheFish92 - well if you're up for working on [HQRM](https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md) then I say go for it? :smile: It would definitely be a great help to the community! 👍 I'm happy to help you on what ever I can (and do the initial reviews). The more help the better I say!

I wrote a blog post containing tips on getting a module up to HQRM standards (https://dscottraynsford.wordpress.com/2016/08/14/tips-for-hqrm-dsc-resources/) that might help get things started.

As for the intellisense, you could use Dynamic Parameter sets instead (https://blogs.technet.microsoft.com/pstips/2014/06/09/dynamic-validateset-in-a-dynamic-parameter/). It will require a bit more work, but it eliminate the hard coding.

@kwirkykat - does this sound like something that would work for you guys?

**Comment by TheFish92** [comment]
@PlagueHO thanks for that. I've touched upon Dynamic Parameters before but have never took the dive and used them, thanks. Actually, it could solve a work-related issue I had with intellisense! (Instead of overwriting tabexpansion2) :) 

Would dynamic parameters filter down into the intellisense for the xComputer resource? I thought this came straight from the schema.mof file?

**Comment by kwirkykat** [comment]
@PlagueHO @TheFish92 Sounds good to me

**Comment by TheFish92** [comment]
Shall we create a new issue for the HQRM discussion & progress?

**Comment by PlagueHO** [comment]
@TheFish92 - definitely! Great idea! Do you want to open the issue?

**Comment by TheFish92** [comment]
@PlagueHO Done :) I'll fix my explanation tomorrow, too close to bed time and I have tests to write! :P

**Comment by PlagueHO** [comment]
This goes back a long way! :grin: @kwirkykat, @lfshr  - I'm aiming to have this up to HQRM over the coming weeks and then we might be able to finally get this move from SystemLocaleDsc over here.

**Comment by lfshr** [comment]
@PlagueHO I know right. I'm going to try and get some of these ancient things of mine off the board if you're up for helping out with PRs?
